devops/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from dashboard import views


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('^$',views.index, name="index"),          # 登陆后台首页接口
    re_path('^login/$',views.login, name="login"),    # login登陆接口
    re_path('^logout/$',views.logout, name="logout"),    # logout退出登录接口
    re_path('^namespace_api/$',views.namespace_api, name="namespace_api"),    # 匿名空间api接口
    re_path('^node_resource/$', views.node_resource, name="node_resource"),   # index页面调用的计算资源接口
    re_path('^export_resource_api/$',views.export_resource_api, name="export_resource_api"),    # 编写yaml获取数据接口
    re_path('^ace_editor/$',views.ace_editor, name="ace_editor"),    # 编写yaml获取数据接口
    path('k8s/', include(('k8s.urls', 'k8s'), namespace='k8s')),            # k8s模块
    path('workload/', include(('workload.urls', 'workload'), namespace='workload')),     # workload模块
    path('loadbalancer/', include(('loadbalancer.urls', 'loadbalancer'), namespace='loadbalancer')),    # loadbalancer模块
    path('storage/', include(('storage.urls', 'storage'), namespace='storage')),    # storage模块，主要用于存储一些文件配置与存储
    path('create_ingress/', views.create_ingress, name='create_ingress'),
    path('files/', include(('files.urls', 'files'), namespace='files')),


]

k8s/urls.py
from django.urls import path,re_path
from k8s import views


urlpatterns = [
    re_path('^nodes/$',views.nodes, name="nodes"),                # node调用的前端页面调用接口
    re_path('^namespaces/$',views.namespaces, name="namespaces"),        # namespaces调用的前端页面展示接口
    re_path('^PersistentVolumes/$',views.PersistentVolumes, name="PersistentVolumes"),        # pv前端展示接口
    re_path('^node_api/$',views.node_api, name="node_api"),                       # 调用的node_api接口
    re_path('^node_details/$',views.node_details, name="node_details"),           # 调用node详情页前端页面展示接口
    re_path('^node_details_pod_list/$',views.node_details_pod_list, name="node_details_pod_list"),    # 调用node详情页，后端api接口
    re_path('^pv_api/$',views.pv_api, name="pv_api"),            # pv调用的后端的api接口
    re_path('^pv_create/$',views.pv_create, name="pv_create"),     # 创建pv调用的前端接口

]

loadbalancer/urls.py
from django.urls import path,re_path
#from devops.loadbalancer import views

from loadbalancer import views

urlpatterns = [
    re_path('^services/$',views.services, name="services"),
    re_path('^ingresses/$',views.ingresses, name="ingresses"),
    re_path('^ingresses_create/$',views.ingresses_create, name="ingresses_create"),
    re_path('^services_api/$',views.services_api, name="services_api"),
    re_path('^ingresses_api/$', views.ingresses_api, name="ingresses_api"),
    re_path('^services_create/$', views.services_create, name="services_create"),

]

loadbalancer/models.py
from django.db import models

# Create your models here.

class Service(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

loadbalancer/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, QueryDict
from kubernetes import client, config
import os, hashlib, random
from devops import k8s_tools  # 导入k8s登陆封装
import json
import time
# services 页面展示
@k8s_tools.self_login_required
def services(request):
    return render(request, "loadbalancer/services.html")

# services_create 创建
@k8s_tools.self_login_required
def services_create(request):
    return render(request, "loadbalancer/services_create.html")




# ingresses 页面展示
@k8s_tools.self_login_required
def ingresses(request):
    return render(request, "loadbalancer/ingresses.html")

# @k8s_tools.self_login_required
# def ingresses_create(request):
#     return render(request, "loadbalancer/ingresses_create.html")
# service list





# services_api 接口
@k8s_tools.self_login_required
def services_api(request):
    code = 0
    msg = ""
    auth_type = request.session.get("auth_type")
    token = request.session.get("token")
    k8s_tools.load_auth_config(auth_type, token)
    core_api = client.CoreV1Api()
    api_instance = client.NetworkingV1Api()
    if request.method == "GET":
        namespace = request.GET.get("namespace")
        data = []
        try:
            for svc in core_api.list_namespaced_service(namespace=namespace).items:
                # print(svc)
                name = svc.metadata.name
                namespace = svc.metadata.namespace
                labels = svc.metadata.labels
                type = svc.spec.type
                cluster_ip = svc.spec.cluster_ip
                ports = []
                for p in svc.spec.ports:  # 不是序列，不能直接返回
                    port_name = p.name
                    port = p.port
                    target_port = p.target_port
                    protocol = p.protocol
                    node_port = ""
                    if type == "NodePort":
                        node_port = " <br> NodePort: %s" % p.node_port

                    port = {'port_name': port_name, 'port': port, 'protocol': protocol, 'target_port': target_port,
                            'node_port': node_port}
                    ports.append(port)

                selector = svc.spec.selector
                create_time = k8s_tools.dt_format(svc.metadata.creation_timestamp)

                # 确认是否关联Pod
                endpoint = ""
                for ep in core_api.list_namespaced_endpoints(namespace=namespace).items:
                    if ep.metadata.name == name and ep.subsets is None:
                        endpoint = "未关联"
                    else:
                        endpoint = "已关联"

                svc = {"name": name, "namespace": namespace, "type": type,
                       "cluster_ip": cluster_ip, "ports": ports, "labels": labels,
                       "selector": selector, "endpoint": endpoint, "create_time": create_time}
                # 根据前端返回的搜索key进行判断，查询关键字返回数据
                search_key = request.GET.get('searchkey', None)
                if search_key:
                    if search_key == name:
                        data.append(svc)
                    elif search_key in name:
                        data.append(svc)
                else:
                    data.append(svc)
                code = 0
                msg = "获取数据成功"
        except Exception as e:
            code = 1
            status = getattr(e, "status")
            if status == 403:
                msg = "没有访问权限"
            else:
                msg = "获取数据失败"
        count = len(data)

        page = int(request.GET.get('page', 1))
        limit = int(request.GET.get('limit'))
        start = (page - 1) * limit
        end = page * limit
        data = data[start:end]

        res = {'code': code, 'msg': msg, 'count': count, 'data': data}
        return JsonResponse(res)

    elif request.method == "DELETE":
        request_data = QueryDict(request.body)
        name = request_data.get("name")
        namespace = request_data.get("namespace")  # 获取命名空间
        try:
            core_api.delete_namespaced_service(namespace=namespace, name=name)  # 删除命名空间下的deployment服务
            code = 0
            msg = "删除成功."
        except Exception as e:
            code = 1
            status = getattr(e, "status")
            if status == 403:
                msg = "没有删除权限"
            else:
                msg = "删除失败！"
        res = {'code': code, 'msg': msg}
        return JsonResponse(res)
    elif request.method == "POST":
        # 检查请求体是否为空
        if not request.body:
            return JsonResponse({'code': 1, 'msg': '请求数据为空'})

        try:
            data = json.loads(request.body)
            print(data)
            # 定义service配置
            service = client.V1Service(
                api_version="v1",
                kind="Service",
                metadata=client.V1ObjectMeta(name=data['name']),
                spec=client.V1ServiceSpec(
                    selector={"app": data['labels']},
                    ports=[client.V1ServicePort(port=int(data['port']), target_port=int(data['targetPort']))],
                    type=data['type']
                )
            )
            try:
                core_api.create_namespaced_service(namespace="default", body=service)
                code = 0
                msg = "创建成功."
            except Exception as e:
                code = 1
                status = getattr(e, "status")
                if status == 403:
                    msg = "没有创建权限"
                elif status == 409:
                    msg = "名称已存在"
                else:
                    msg = "创建失败！"
            res = {'code': code, 'msg': msg}
            return JsonResponse(res)
            # 正常处理数据
            return JsonResponse({'code': 0, 'msg': '创建成功'})
        except json.JSONDecodeError:
            return JsonResponse({'code': 1, 'msg': '请检查输入是否正确'})



# ingresses_api 接口
@k8s_tools.self_login_required
def ingresses_api(request):
    code = 0
    msg = ""
    auth_type = request.session.get("auth_type")
    token = request.session.get("token")
    k8s_tools.load_auth_config(auth_type, token)
    networking_api = client.NetworkingV1Api()
    if request.method == "GET":
        namespace = request.GET.get("namespace")
        data = []
        try:
            for ing in networking_api.list_namespaced_ingress(namespace=namespace).items:
                # print(ing)    # 获取ingresses所有数据
                name = ing.metadata.name
                namespace = ing.metadata.namespace
                labels = ing.metadata.labels
                service = "None"
                http_hosts = "None"
                for h in ing.spec.rules:
                    host = h.host
                    path = ("/" if h.http.paths[0].path is None else h.http.paths[0].path)
                    service_name = h.http.paths[0].backend.service.name
                    '''
                        根据查询结果查询数据
                        print(h.http.paths[0])          
                        print(h.http.paths[0].backend)
                        print(h.http.paths[0].backend.service_name)
                    '''
                    #print("path:",h.http.paths[0])
                    #print("backend:",h.http.paths[0].backend)
                    #print("serviceName: ",h.http.paths[0].backend.service.name)
                    service_port = h.http.paths[0].backend.service.port.number
                    http_hosts = {'host': host, 'path': path, 'service_name': service_name,
                                  'service_port': service_port}
                    #print(http_hosts)
                #https_hosts = "None"
                if ing.spec.tls is None:
                    https_hosts = ing.spec.tls
                else:
                    for tls in ing.spec.tls:
                        host = tls.hosts[0]
                        secret_name = tls.secret_name
                        https_hosts = {'host': host, 'secret_name': secret_name}

                create_time = k8s_tools.dt_format(ing.metadata.creation_timestamp)

                ing = {"name": name, "namespace": namespace, "labels": labels, "http_hosts": http_hosts,
                       "https_hosts": https_hosts, "service": service, "create_time": create_time}
                # 根据前端返回的搜索key进行判断，查询关键字返回数据
                search_key = request.GET.get('searchkey', None)
                if search_key:
                    if search_key == name:
                        data.append(ing)
                    elif search_key in name:
                        data.append(ing)
                else:
                    data.append(ing)
                code = 0
                msg = "获取数据成功"
        except Exception as e:
            code = 1
            status = getattr(e, "status")
            if status == 403:
                msg = "没有访问权限"
            else:
                msg = "获取数据失败"
        count = len(data)

        page = int(request.GET.get('page', 1))
        limit = int(request.GET.get('limit'))
        start = (page - 1) * limit
        end = page * limit
        data = data[start:end]

        res = {'code': code, 'msg': msg, 'count': count, 'data': data}
        return JsonResponse(res)

    elif request.method == "DELETE":
        request_data = QueryDict(request.body)
        name = request_data.get("name")
        namespace = request_data.get("namespace")  # 获取命名空间
        try:
            networking_api.delete_namespaced_ingress(namespace=namespace, name=name)  # 删除命名空间下的deployment服务
            code = 0
            msg = "删除成功."
        except Exception as e:
            code = 1
            status = getattr(e, "status")
            if status == 403:
                msg = "没有删除权限"
            else:
                msg = "删除失败！"
        res = {'code': code, 'msg': msg}
        return JsonResponse(res)


def ingresses_create(request):
    code = 0
    msg = ""
    auth_type = request.session.get("auth_type")
    token = request.session.get("token")

templates/loadbalancer/ingresses.html
{% extends "base.html" %}

<!--头部-->
{% block title %} ingresses节点 {% endblock %}
<!-停留的样式-->
<!--layui-nav-itemed 为开关-->
{% block nav-item-3 %} layui-nav-itemed {% endblock %}

<!--layui-this 停留的背景颜色-->
{% block nav-this-3-2 %}layui-this {% endblock %}


<!--内容-->
{% block content %}
    <div class="layui-card">
        <div class="layui-card-body">
            <table id="demo" lay-filter="test"></table>
        </div>
    </div>
{% endblock %}



<!--js代码-->
{% block js %}
    <script type="text/html" id="toolbarDemo">
        <!--增加一个输入框-->
        <input type="text" name="name" class="layui-input" style="width: 150px;height: 30px;float: left">
        <button class="layui-btn layui-btn-sm" style="float: left" id="searchBtn">搜索</button>
        <a href="{% url 'loadbalancer:ingresses_create' %}" class="layui-btn layui-btn-sm" style="float: left">创建</a>
    </script>


    <script type="text/html" id="barDemo">
        <a class="layui-btn layui-btn-xs layui-btn-primary" lay-event="edit">YAML</a>
        <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
    </script>

    <script>

        // 获取当前命名空间
        var storage = window.sessionStorage;
        var namespace = storage.getItem("namespace");
        console.log(namespace)


        layui.use('table', function () {
            var table = layui.table;
            var layer = layui.layer;
            var $ = layui.jquery;

            table.render({
                elem: '#demo'
                , url: '{% url "loadbalancer:ingresses_api" %}?namespace=' + namespace      // 调用接口数据，并返回全局命名空间值
                , toolbar: '#toolbarDemo' //开启头部工具栏，并为其绑定左侧模板
                , defaultToolbar: ['filter', 'exports', 'print', { //自定义头部工具栏右侧图标。如无需自定义，去除该参数即可
                    title: '提示'
                    , layEvent: 'LAYTABLE_TIPS'
                    , icon: 'layui-icon-tips'
                }]
                , title: '数据表'
                , skin: 'line'         // 取消表格竖线
                , cols: [[
                    //{field: 'id', title: '序号', width: 80, fixed: 'left', type: 'numbers'},   // 序号排序，使用type：'numbers'
                    {field: 'name', title: '名称', sort: true, width: 300}
                    , {field: 'namespace', title: '命名空间', width: 200, sort: true}
                    , {field: 'http_hosts', title: 'HTTP', templet: httpFormat}
                    , {field: 'https_hosts', title: 'HTTPS', templet: httpsFormat}
                    , {field: 'service', title: '关联 Service', templet: serviceFormat}
                    , {field: 'create_time', title: '创建时间', width: 200}
                    , {fixed: 'right', title: '操作', toolbar: '#barDemo', width: 150}
                ]]
                , page: true      // 设置分页
                , id: "ing"      // 设置表格重载， 这里使用必须是id："值"
            });

            // 标签格式化，是一个对象
            function httpFormat(d) {
                return "域名: " + d.http_hosts.host + '<br>' + "路径: " + d.http_hosts.path + '<br>'
            }

            function httpsFormat(d) {
                if (d.https_hosts != null) {
                    return "域名: " + d.https_hosts.host + '<br>' + "证书Secret名称: " + d.https_hosts.secret_name + '<br>';
                } else {
                    return "None"
                }
            }

            function serviceFormat(d) {
                return "名称: " + d.http_hosts.service_name + '<br>' + "端口: " + d.http_hosts.service_port + '<br>';
            }

            //监听行工具事件
            table.on('tool(test)', function (obj) {
                var data = obj.data;
                //console.log(obj)
                if (obj.event === 'del') {
                    console.log(data)
                    layer.confirm('是否确定删除' + data["name"] + "这个命令空间吗", function (index) {
                        csrf_token = $('[name=csrfmiddlewaretoken]').val();

                        $.ajax({
                            type: "DELETE",
                            url: "{% url "loadbalancer:ingresses_api" %}",
                            data: data,
                            headers: {"X-CSRFToken": csrf_token},
                            success: function (res) {
                                if (res.code == 0) {
                                    layer.msg(res.msg, {icon: 6});
                                    obj.del()  // 页面删除
                                } else {
                                    layer.msg(res.msg, {icon: 5})
                                }
                            },
                            error: function () {

                            },
                        });
                    });
                } else if (obj.event === 'edit') {
                   layer.open({
                        title: 'YAML',
                        type: 2,
                        area: ['60%', '60%'],
                        content: "{% url 'ace_editor' %}?resource=ingresses&" + 'namespace=' + data['namespace'] + '&name=' + data['name'],
                    });
                }
            });

            // 搜索功能
            $(document).on('click', '#searchBtn', function () {
                // 获取搜索的值
                var input_val = $('input[name=name]').val();

                // 判断用户是点击搜索按钮是否有值，没有就刷新当前页面，获取所有，否则就返回后端接口，刷新
                if (input_val == "" || input_val == null || input_val == undefined) { // "",null,undefined
                    console.log("为空")
                    window.parent.location.reload()
                } else {
                    table.reload('ing', {
                        where: { //设定异步数据接口的额外参数，任意设
                            // 要传回的key
                            searchkey: input_val
                        }
                        , page: {
                            curr: 1 //重新从第 1 页开始
                        }
                    }); //只重载数据
                }

            });


        });

    </script>


{% endblock %}

templates/loadbalancer/ingresses_create.html
{% extends 'base.html' %}
{% block title %}ingress{% endblock %}
{% block nav-item-3 %}layui-nav-itemed{% endblock %}
{% block nav-this-3-2 %}layui-this{% endblock %}
{% block content %}
<span class="layui-breadcrumb">
  <a href="#">首页</a>
  <a href="#">ingress</a>
  <a><cite>create</cite></a>
</span>
<hr>

<div class="layui-card">
    <div class="layui-card-body">

    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
      <legend>创建ingress</legend>
    </fieldset>

    <form class="layui-form" id="ingressForm">
        {% csrf_token %}
        <div class="layui-form-item">
            <label class="layui-form-label">名称：</label>
            <div class="layui-input-block">
              <input type="text" name="name" lay-verify="required" lay-reqtext="名称是必填项，不能为空！" placeholder="" autocomplete="off" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">命名空间：</label>
            <div class="layui-input-block">
                <select name="namespace" lay-verify="required" id="ns">
                    <!-- Options will be populated by JavaScript -->
                </select>
            </div>
         </div>

        <div class="layui-form-item">
            <label class="layui-form-label">host：</label>
            <div class="layui-input-block">
              <input type="text" name="host" lay-verify="required" lay-reqtext="名称是必填项，不能为空！" placeholder="" autocomplete="off" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">path：</label>
            <div class="layui-input-block">
              <input type="text" name="path" lay-verify="required" lay-reqtext="名称是必填项，不能为空！" placeholder="" autocomplete="off" class="layui-input">
            </div>
        </div>

        <label class="layui-form-label">关联service：</label>
        <div class="layui-input-block">
            <select id="service-select" name="selector" lay-verify="required" lay-reqtext="名称是必填项，不能为空！" class="layui-input">
                <option value="">请选择一个服务</option>
            </select>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">ServicePort：</label>
            <div class="layui-input-block">
              <input type="text" name="port" lay-verify="required" lay-reqtext="名称是必填项，不能为空！" placeholder="" autocomplete="off" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">标签：</label>
            <div class="layui-input-block">
              <input type="text" name="labels" lay-verify="required" lay-reqtext="标签是必填项，不能为空！" placeholder="示例: project=ms,app=gateway" autocomplete="off" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-input-block">
              <button type="button" class="layui-btn" id="submitBtn">立即提交</button>
              <button type="reset" class="layui-btn layui-btn-primary">重置</button>
            </div>
        </div>
    </form>

    </div>
</div>

{% endblock %}

{% block js %}
<script>
layui.use(['form'], function(){
  var form = layui.form;
  var $ = layui.jquery;

  // Populate the namespace select dynamically
  var namespace = window.sessionStorage.getItem("namespace");
  if (namespace) {
    $('#ns').append('<option value="' + namespace + '">' + namespace + '</option>');
    form.render('select');  // Re-render the select element
  }

  // Populate the services select dynamically
  window.onload = function() {
    // 使用 AJAX 请求获取服务数据
    var xhr = new XMLHttpRequest();
    xhr.open("GET", "/loadbalancer/services_api/?namespace=default&page=1&limit=10", true);
    xhr.onreadystatechange = function () {
      if (xhr.readyState === 4 && xhr.status === 200) {
        var response = JSON.parse(xhr.responseText);
        var services = response.data;  // 假设返回的 JSON 数据中包含一个名为 data 的数组
        var select = document.getElementById("service-select");

        // 遍历服务数据并动态添加选项到下拉选择框
        services.forEach(function(service) {
          var option = document.createElement("option");
          option.text = service.name;
          option.value = service.name;  // 使用服务的名称作为值
          select.appendChild(option);
        });

        // 重新渲染 select 元素
        form.render('select');
      }
    };
    xhr.send();
  };

  $('#submitBtn').click(function () {
    var formData = {
        name: $('input[name="name"]').val(),
        namespace: $('select[name="namespace"]').val(),
        selector: $('select[name="selector"]').val(),
        labels: $('input[name="labels"]').val(),
        port: $('input[name="port"]').val(),
        path: $('input[name="path"]').val(),
        host: $('input[name="host"]').val()

    };

    var datajson = JSON.stringify(formData);

    $.ajax({
        url: '{% url "loadbalancer:ingresses_create" %}',
        type: "POST",
        contentType: 'application/json',
        headers: { 'X-CSRFToken': $('[name="csrfmiddlewaretoken"]').val() },
        data: datajson,
        dataType: 'json',
        success: function (res) {
            if (res.code == 0) {
                layer.msg(res.msg, {icon: 6});
                window.location.href = "{% url 'loadbalancer:ingresses' %}";
            } else {
                layer.msg(res.msg, {icon: 5});
            }
        },
        error: function (xhr) {
            layer.msg("服务器接口异常", {icon: 5});
            console.log(xhr.responseText);
        }
    });

    return false;  // 阻止表单的默认提交行为
  });
});
</script>
{% endblock %}

templates/loadbalancer/services.html
{% extends "base.html" %}

<!--头部-->
{% block title %} services节点 {% endblock %}
<!-停留的样式-->
<!--layui-nav-itemed 为开关-->
{% block nav-item-3 %} layui-nav-itemed {% endblock %}

<!--layui-this 停留的背景颜色-->
{% block nav-this-3-1 %}layui-this {% endblock %}


<!--内容-->
{% block content %}
    <div class="layui-card">
        <div class="layui-card-body">
            <table id="demo" lay-filter="test"></table>
        </div>
    </div>
{% endblock %}



<!--js代码-->
{% block js %}
    <script type="text/html" id="toolbarDemo">
        <!--增加一个输入框-->
        <input type="text" name="name" class="layui-input" style="width: 150px;height: 30px;float: left">
        <button class="layui-btn layui-btn-sm" style="float: left" id="searchBtn">搜索</button>
        <a href="{% url 'loadbalancer:services_create' %}" class="layui-btn layui-btn-sm" style="float: left">创建</a>
    </script>


    <script type="text/html" id="barDemo">
        <a class="layui-btn layui-btn-xs layui-btn-primary" lay-event="edit">YAML</a>
        <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
    </script>

    <script>

        // 获取当前命名空间
        var storage = window.sessionStorage;
        var namespace = storage.getItem("namespace");
        console.log(namespace)


        layui.use('table', function () {
            var table = layui.table;
            var layer = layui.layer;
            var $ = layui.jquery;

            table.render({
                elem: '#demo'
                , url: '{% url "loadbalancer:services_api" %}?namespace=' + namespace      // 调用接口数据，并返回全局命名空间值
                , toolbar: '#toolbarDemo' //开启头部工具栏，并为其绑定左侧模板
                , defaultToolbar: ['filter', 'exports', 'print', { //自定义头部工具栏右侧图标。如无需自定义，去除该参数即可
                    title: '提示'
                    , layEvent: 'LAYTABLE_TIPS'
                    , icon: 'layui-icon-tips'
                }]
                , title: '数据表'
                , skin: 'line'         // 取消表格竖线
                , cols: [[
                    {field: 'name', title: '名称', sort: true, width: 100}
                    , {field: 'namespace', title: '命名空间', width: 100, sort: true}
                    , {field: 'type', title: '类型', width: 120, sort: true}
                    , {field: 'cluster_ip', title: '集群IP', width: 150}
                    , {field: 'ports', title: '端口信息', templet: portsFormat}
                    , {field: 'labels', title: '标签', templet: labelsFormat}
                    , {field: 'selector', title: 'Pod 标签选择器', templet: selecotrFormat}
                    , {field: 'endpoint', title: '后端 Pod'}
                    , {field: 'create_time', title: '创建时间', width: 200}
                    , {fixed: 'right', title: '操作', toolbar: '#barDemo', width: 150}
                ]]
                , page: true      // 设置分页
                , id: "svc"      // 设置表格重载， 这里使用必须是id："值"
            });

            function labelsFormat(d) {
                result = "";
                if (d.labels == null) {
                    return "None"
                } else {
                    for (let key in d.labels) {
                        result += '<span style="border: 1px solid #d6e5ec;border-radius: 8px">' +
                            key + ':' + d.labels[key] +
                            '</span><br>'
                    }
                    return result
                }
            }

            function selecotrFormat(d) {
                result = "";
                for (let key in d.selector) {
                    result += '<span style="border: 1px solid #d6e5ec;border-radius: 8px">' +
                        key + ':' + d.selector[key] +
                        '</span><br>'
                }
                return result
            }

            function portsFormat(d) {
                result = "";
                for (let key in d.ports) {
                    data = d.ports[key];
                    result += '名称: ' + data.port_name + '<br>' +
                        '端口: ' + data.port + '<br>' +
                        '协议: ' + data.protocol + '<br>' +
                        '容器端口: ' + data.target_port + '<br>'
                }
                return result
            }

            //监听行工具事件
            table.on('tool(test)', function (obj) {
                var data = obj.data;
                //console.log(obj)
                if (obj.event === 'del') {
                    console.log(data)
                    layer.confirm('是否确定删除' + data["name"] + "这个命令空间吗", function (index) {
                        csrf_token = $('[name=csrfmiddlewaretoken]').val();

                        $.ajax({
                            type: "DELETE",
                            url: "{% url "loadbalancer:services_api" %}",
                            data: data,
                            headers: {"X-CSRFToken": csrf_token},
                            success: function (res) {
                                if (res.code == 0) {
                                    layer.msg(res.msg, {icon: 6});
                                    obj.del()  // 页面删除
                                } else {
                                    layer.msg(res.msg, {icon: 5})
                                }
                            },
                            error: function () {

                            },
                        });
                    });
                } else if (obj.event === 'edit') {
                    layer.open({
                        title: 'YAML',
                        type: 2,
                        area: ['60%', '60%'],
                        content: "{% url 'ace_editor' %}?resource=services&" + 'namespace=' + data['namespace'] + '&name=' + data['name'],
                    });
                }
            });

            // 搜索功能
            $(document).on('click', '#searchBtn', function () {
                // 获取搜索的值
                var input_val = $('input[name=name]').val();

                // 判断用户是点击搜索按钮是否有值，没有就刷新当前页面，获取所有，否则就返回后端接口，刷新
                if (input_val == "" || input_val == null || input_val == undefined) { // "",null,undefined
                    console.log("为空")
                    window.parent.location.reload()
                } else {
                    table.reload('svc', {
                        where: { //设定异步数据接口的额外参数，任意设
                            // 要传回的key
                            searchkey: input_val
                        }
                        , page: {
                            curr: 1 //重新从第 1 页开始
                        }
                    }); //只重载数据
                }

            });


        });

    </script>


{% endblock %}