devops/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from dashboard import views


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('^$',views.index, name="index"),          # 登陆后台首页接口
    re_path('^login/$',views.login, name="login"),    # login登陆接口
    re_path('^logout/$',views.logout, name="logout"),    # logout退出登录接口
    re_path('^namespace_api/$',views.namespace_api, name="namespace_api"),    # 匿名空间api接口
    re_path('^node_resource/$', views.node_resource, name="node_resource"),   # index页面调用的计算资源接口
    re_path('^export_resource_api/$',views.export_resource_api, name="export_resource_api"),    # 编写yaml获取数据接口
    re_path('^ace_editor/$',views.ace_editor, name="ace_editor"),    # 编写yaml获取数据接口
    path('k8s/', include(('k8s.urls', 'k8s'), namespace='k8s')),            # k8s模块
    path('workload/', include(('workload.urls', 'workload'), namespace='workload')),     # workload模块
    path('loadbalancer/', include(('loadbalancer.urls', 'loadbalancer'), namespace='loadbalancer')),    # loadbalancer模块
    path('storage/', include(('storage.urls', 'storage'), namespace='storage')),    # storage模块，主要用于存储一些文件配置与存储
    path('create_ingress/', views.create_ingress, name='create_ingress'),
    path('files/', include(('files.urls', 'files'), namespace='files')),


]

files/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('upload', views.upload, name='upload'),
    path('list', views.list, name='list'),
    path('files_api', views.files_api, name='files_api'),
    path('preview',views.preview_file,name="preview"),
    # 其他路径...
]

k8s/urls.py
from django.urls import path,re_path
from k8s import views


urlpatterns = [
    re_path('^nodes/$',views.nodes, name="nodes"),                # node调用的前端页面调用接口
    re_path('^namespaces/$',views.namespaces, name="namespaces"),        # namespaces调用的前端页面展示接口
    re_path('^PersistentVolumes/$',views.PersistentVolumes, name="PersistentVolumes"),        # pv前端展示接口
    re_path('^node_api/$',views.node_api, name="node_api"),                       # 调用的node_api接口
    re_path('^node_details/$',views.node_details, name="node_details"),           # 调用node详情页前端页面展示接口
    re_path('^node_details_pod_list/$',views.node_details_pod_list, name="node_details_pod_list"),    # 调用node详情页，后端api接口
    re_path('^pv_api/$',views.pv_api, name="pv_api"),            # pv调用的后端的api接口
    re_path('^pv_create/$',views.pv_create, name="pv_create"),     # 创建pv调用的前端接口

]

loadbalancer/urls.py
from django.urls import path,re_path
#from devops.loadbalancer import views

from loadbalancer import views

urlpatterns = [
    re_path('^services/$',views.services, name="services"),
    re_path('^ingresses/$',views.ingresses, name="ingresses"),
    re_path('^ingresses_create/$',views.ingresses_create, name="ingresses_create"),
    re_path('^services_api/$',views.services_api, name="services_api"),
    re_path('^ingresses_api/$', views.ingresses_api, name="ingresses_api"),
    re_path('^services_create/$', views.services_create, name="services_create"),

]

workload/urls.py
from django.urls import path,re_path
from workload import views


urlpatterns = [
    re_path('^deployments/$',views.deployments, name="deployments"),             # deployments展示页面接口
    re_path('^deployments_create/$',views.deployments_create, name="deployments_create"),   # deployments创建页面接口
    re_path('^daemonsets/$',views.daemonsets, name="daemonsets"),                       # daemonsets 展示页面接口
    re_path('^daemonsets_create/$',views.daemonsets_create, name="daemonsets_create"),
    re_path('^statefulsets/$',views.statefulsets, name="statefulsets"),
    re_path('^statefulsets_create/$',views.statefulsets_create, name="statefulsets_create"),
    re_path('^pods/$',views.pods, name="pods"),
    re_path('^deployments_api/$',views.deployments_api, name="deployments_api"),
    re_path('^deployments_details/$',views.deployments_details, name="deployments_details"),
    re_path('^daemonsets_api/$',views.daemonsets_api, name="daemonsets_api"),
    re_path('^statefulsets_api/$', views.statefulsets_api, name="statefulsets_api"),
    re_path('^pods_api/$', views.pods_api, name="pods_api"),
    re_path('^replicaset_api/$', views.replicaset_api, name="replicaset_api"),    # 用于deployments详情页查询数据
    re_path('^pods_log/$', views.pods_log, name="pods_log"),    # 用于pods的日志查看
    re_path('^terminal/$', views.terminal, name="terminal"),    # 用于pod的容器终端
]

templates/ace_editor.html
<link rel="stylesheet" href="/static/layui/css/layui.css">
<!--必须设置高度，否则无法显示-->
<div  id="code-editor" style="height: 98%;width:98%;"></div>

<script src="/static/ace/ace.js" type="text/javascript" charset="utf-8"></script>
<script src="/static/ace/theme/theme-chrome.js" type="text/javascript" charset="utf-8"></script>
<script src="/static/ace/mode/mode-yaml.js" type="text/javascript" charset="utf-8"></script>
<script src="/static/layui/layui.js"></script>
{% csrf_token %}
<script>
     //初始化对象
     var editor = ace.edit("code-editor");

     //设置编辑器样式，对应theme-*.js文件
     editor.setTheme("ace/theme/chrome");
     //设置代码语言，对应mode-*.js文件
     editor.session.setMode("ace/mode/yaml");
     //设置打印线是否显示
     editor.setShowPrintMargin(false);
     //字体大小
     editor.setFontSize(16);
     //设置只读（true时只读，用于展示代码）
     editor.setReadOnly(false);

     // 获取编辑内容
     /*
     editor.getSession().on("change", function () {
         var code = editor.getValue();
         console.log(code)
     }); */

     layui.use(['layer'], function(){
        var $ = layui.jquery;
        layer = layui.layer;  // 获取到使用的组件

        // 后端传：命名空间，资源，名称 。传过来的不是json对象，要转换
        var namespace = "{{ data.namespace }}";
        var resource = "{{ data.resource }}";
        var name = "{{ data.name }}";

        $.ajax({
           url: '{% url "export_resource_api" %}?' + 'namespace=' + namespace + '&resource=' + resource + "&name=" + name,
           type: 'GET',
           // 提交成功回调函数
           success: function (res) {
               if(res.code == '0') {
                   editor.setValue(res.data);   // 设置编辑内容
               } else {
                   layer.msg(res.msg, {icon: 5})
               }
           },
           // 访问接口失败函数
           error: function (res) {
               layer.msg("服务器接口异常！" , {icon:5})
           }
        })
    })

</script>

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/static/layui/css/layui.css">
    <style>
        .layui-table-cell {
            height: 100%;
        }
    </style>
</head>
<body class="layui-layout-body">
{% csrf_token %}
{% block body_first %}{% endblock %}
<div class="layui-layout layui-layout-admin">
    <div class="layui-header layui-bg-cyan">
        <div class="layui-logo" style="font-weight: bold;font-size: 26px;color: white">k8s 管理平台</div>
        <!-- 头部区域（可配合layui已有的水平导航） -->
        <ul class="layui-nav layui-layout-left">
            <!--namespace匿名空间选择-->
            <div class="namespace layui-nav-item" style="width: 200px">
                <select name="namespace" id="nsSelect" style="width: 200px; height: 30px; font-size: 20px;">

                </select>
            </div>
        </ul>
        <ul class="layui-nav layui-layout-right">
            <!--头像和用户行注释-->
            <!--
            <li class="layui-nav-item">
                <a href="javascript:;">
                    <img src="/static/img/touxiang.jpeg" class="layui-nav-img">
                    test
                </a>
                <dl class="layui-nav-child">
                    <dd><a href="">基本资料</a></dd>
                    <dd><a href="">安全设置</a></dd>
                </dl>
            </li>
            -->
            <li class="layui-nav-item"><a href="{% url "logout" %}"><i class="layui-icon layui-icon-logout"
                                                                       style="font-size: 25px;color: #1E9FFF;"></i></a>
            </li>
        </ul>
    </div>

    <div class="layui-side layui-bg-black">
        <div class="layui-side-scroll layui-bg-cyan">
            <!-- 左侧导航区域（可配合layui已有的垂直导航） -->
            <ul class="layui-nav layui-nav-tree layui-bg-cyan" lay-filter="test">
                <li class="layui-nav-item"><a href="{% url "index" %}"><i class="layui-icon layui-icon-console"
                                                                          style="font-size: 15px;color: #1E9FFF;">&nbsp;&nbsp;</i>仪表盘</a>
                </li>
                <li class="layui-nav-item {% block nav-item-1 %} {% endblock %}">
                    <a class="" href="javascript:;"><i class="layui-icon layui-icon-component"
                                                       style="font-size: 15px;color: #1E9FFF;">&nbsp;&nbsp;</i>kubernetes</a>
                    <dl class="layui-nav-child">
                        <dd><a href="{% url "k8s:nodes" %}" class="{% block nav-this-1-1 %} {% endblock %} ">Node</a>
                        </dd>
                        <dd><a href="{% url "k8s:namespaces" %}" class="{% block nav-this-1-2 %} {% endblock %} ">Namespces</a>
                        </dd>
                        <dd><a href="{% url "k8s:PersistentVolumes" %}"
                               class="{% block nav-this-1-3 %} {% endblock %} ">Persistent Volumes</a></dd>
                    </dl>
                </li>
                <li class="layui-nav-item {% block nav-item-2 %}{% endblock %}">
                    <a href="javascript:;"><i class="layui-icon layui-icon-app"
                                              style="font-size: 15px;color: #1E9FFF;">&nbsp;&nbsp;</i>工作负载</a>
                    <dl class="layui-nav-child">
                        <dd><a href="{% url "workload:deployments" %}" class="{% block nav-this-2-1 %}{% endblock %}">Deployments</a>
                        </dd>
                        <dd><a href="{% url "workload:daemonsets" %}" class="{% block nav-this-2-2 %}{% endblock %}">Daemon Sets</a></dd>
                        <dd><a href="{% url "workload:statefulsets" %}"  class="{% block nav-this-2-3 %}{% endblock %}">Stateful Sets</a></dd>
                        <dd><a href="{% url "workload:pods" %}"   class="{% block nav-this-2-4 %}{% endblock %}">pods</a></dd>
                    </dl>
                </li>
                <li class="layui-nav-item {% block nav-item-3 %}{% endblock %}">
                    <a href="javascript:;"><i class="layui-icon layui-icon-app"
                                              style="font-size: 15px;color: #1E9FFF;">&nbsp;&nbsp;</i>负载均衡</a>
                    <dl class="layui-nav-child">
                        <dd><a href="{% url "loadbalancer:services" %}" class="{% block nav-this-3-1 %}{% endblock %}">Services</a></dd>
                        <dd><a href="{% url "loadbalancer:ingresses" %}"  class="{% block nav-this-3-2 %}{% endblock %}">Ingresses</a></dd>
                    </dl>
                </li>
                <li class="layui-nav-item {% block nav-item-4 %}{% endblock %}">
                    <a href="javascript:;"><i class="layui-icon layui-icon-template-1"
                                              style="font-size: 15px;color: #1E9FFF;">&nbsp;&nbsp;</i>存储配置</a>
                    <dl class="layui-nav-child">
                        <dd><a href="{% url "storage:pvc" %}" class="{% block nav-this-4-1 %}{% endblock %}">Persistent Volume Claims</a></dd>
                        <dd><a href="{% url "storage:configmaps" %}" class="{% block nav-this-4-2 %}{% endblock %}">Config Maps</a></dd>
                        <dd><a href="{% url "storage:secrets" %}" class="{% block nav-this-4-3 %}{% endblock %}">Secrets</a></dd>
                    </dl>
                </li>
                <li class="layui-nav-item {% block nav-item-5 %}{% endblock %}">
                    <a href="javascript:;"><i class="layui-icon layui-icon-template-1"
                                              style="font-size: 15px;color: #1E9FFF;">&nbsp;&nbsp;</i>数据集</a>
                    <dl class="layui-nav-child">
                        <dd><a href="{% url "files:list" %}" class="{% block nav-this-5-1 %}{% endblock %}">文件</a></dd>
                    </dl>
                </li>
            </ul>
        </div>
    </div>

    <div class="layui-body" style="background-color: #eeeeee">
        <!-- 内容主体区域 -->
        <div style="padding: 15px;">{% block content %}{% endblock %}</div>
    </div>

{#    <div class="layui-footer" style="text-align: center; height: 35px" >#}
{#        <!-- 底部固定区域 -->#}
{#       Copyright © 2019 版权所有#}
{#    </div>#}
</div>
<script src="/static/layui/layui.js"></script>
{% block js %}{% endblock %}
<script>
    //JavaScript代码区域
    layui.use(['element', 'layer'], function () {
        var element = layui.element;
        var $ = layui.jquery;
        var layer = layui.layer;   // 弹窗


        $.ajax({
            type: "GET",
            url: "{% url 'namespace_api' %}",    // 请求的url接口
            //timeout: 5000,    // 设置超时时间
            async: false,  // 关闭异步请求
            success: function (res) {
                if (res.code == 0) {
                    // 把数据回写到页面上，通过循环传参数
                    for (let i in res.data) {
                        row = res.data[i];
                        $("#nsSelect").append('<option value=' + row.name + '>' + row.name + '</option>')
                    }

                    // 设置默认命名空间
                    $("#nsSelect").val("default")
                } else {
                    $("#nsSelect").append('<option value="default">default</option>');
                    $("#nsSelect").attr("disabled", "disabled");
                }
            },
            error: function () {
                layer.msg("服务器接口异常", {icon: 5})
            },
        });


        // 将当前选择的命名空间保存到本地浏览器session存储用户，以便其他页面能获取到当前选择的命名空间
        var storage = window.sessionStorage;

        // 定义获取命名空间
        var namespace = storage.getItem("namespace");
        // 通过ID获取当前命令空间值
        var current_ns = $("#nsSelect").val();

        // 判断是否有值
        if (namespace == null) {
            storage.setItem("namespace", current_ns)

        } else {
            $("#nsSelect").val(namespace)
        }

        // 如果这里面的值发生改变，就触发一下的值
        $("#nsSelect").change(function () {
            var curren_ns = $("#nsSelect").val()
            storage.setItem("namespace", curren_ns)

            // 选择命名空间后，刷新页面
            location.reload()

        })

        // 点击页面退出，关闭接口

    });
</script>
</body>
</html>

templates/index.html
{% extends "base.html" %}

<!--头部-->
{% block title %} 首页 {% endblock %}


<!--内容-->
{% block content %}
    <style>
        .dashboard-ns {
            width: 130px;
            height: 50px;
            border: 1px solid #ebeef5;
            border-radius: 5px;
            box-shadow: 0 1px 1px 0 #c2c2c2;
            text-align: center;
            line-height: 50px;
            font-size: 18px;
            color: #2F4056;
            margin: 5px;
            float: left;
            overflow: hidden;  /* 溢出自动隐藏*/
            text-overflow: ellipsis; /* 溢出用省略号*/
            white-space: nowrap;  /* nowrap:规定段落中的文本不进行换行 ，与上面配合使用 */
        }
        .chart {
            width: 250px;
            height:200px;
            float: left;
            margin-left: 10%
        }
        .node {
            border: 1px solid #ebeef5;
            border-radius: 5px;
            box-shadow: 0 1px 1px 0 #c2c2c2;
            height: 180px;
            width: 380px;
            float: left;
            margin: 6px
        }
        .node:hover {
            box-shadow: 0 2px 2px 0 #c2c2c2;
            cursor:pointer;
        }
        .pv {
            border: 1px solid #ebeef5;
            border-radius: 5px;
            box-shadow: 0 1px 1px 0 #c2c2c2;
            height: 150px;
            width: 380px;
            float: left;
            margin: 6px;
            text-overflow: ellipsis;
        }
        .pv-notice {
            background-color: #f4f4f5;
            color: #909399;
            padding: 5px;
            margin-left: 30%;
            font-size: 16px;
        }
        /* 背景 */
        .layui-badge {
            font-size: 14px;
            padding: 1px
        }
    </style>
   <div class="layui-col-md12 layui-col-space10">
        <div class="layui-col-md12 layui-col-space10">
            <div class="layui-col-md6">
                <div class="layui-card">
                    <div class="layui-card-header">命名空间</div>
                    <div class="layui-card-body" style="height: 400px;overflow: auto" id="dashboard-ns">

                    </div>
                </div>
            </div>
            <div class="layui-col-md6">
                <div class="layui-card">
                    <div class="layui-card-header">计算资源</div>
                    <div class="layui-card-body" style="height: 400px;overflow: auto">
                          <div id="chart1" class="chart"></div>
                          <div id="chart2" class="chart"></div>
                          <div id="chart3" class="chart"></div>
                          <div id="chart4" class="chart"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="layui-col-md12 layui-col-space10">
            <div class="layui-col-md6">
                <div class="layui-card">
                    <div class="layui-card-header">存储资源</div>
                    <div class="layui-card-body" style="height: 400px;overflow: auto">
                        {% if pv_list %}
                          {% for pv in pv_list %}
                              <div class="pv">
                                  <div class="layui-card-header">{{ pv.pv_name }}</div>

                                  <div class="layui-card-body" style="line-height: 30px">
                                      卷申请：<span class="layui-badge layui-bg-orange">{{ pv.claim }}</span><br>
                                      容量/状态：<span class="layui-badge layui-bg-green">{{ pv.capacity }}</span>
                                      <span class="layui-badge layui-bg-gray">/</span>
                                    <span class="layui-badge layui-bg-green">{{ pv.status }}</span><br>
                                      创建时间：
                                    <span class="layui-badge layui-bg-blue">{{ pv.create_time }}</span>
                                 </div>
                             </div>
                          {% endfor %}
                        {% else %}
                            <span class="pv-notice">此处显示PV资源，但是您目前并未创建！</span>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="layui-col-md6">
                <div class="layui-card">
                    <div class="layui-card-header">节点状态</div>
                    <div class="layui-card-body" style="height: 400px;overflow: auto;">
                          {% for k,v in node_resouces.items %}
                          <a href="{% url "k8s:node_details" %}?node_name={{ k }}">
                          <div class="node">
                              <div class="layui-card-header">{{ k }}</div>
                              <div class="layui-card-body" style="line-height: 30px">
                                CPU：
                                <span class="layui-badge layui-bg-orange"> 已分配 {{ v.cpu_requests }} 核</span>
                                <span class="layui-badge layui-bg-gray">/</span>
                                <span class="layui-badge layui-bg-green">可分配 {{ v.allocatable_cpu }} 核</span>
                                <span class="layui-badge layui-bg-gray">/</span>
                                <span class="layui-badge layui-bg-blue">总量 {{ v.capacity_cpu }} 核</span><br>
                                内存：
                                <span class="layui-badge layui-bg-orange"> 已分配 {{ v.memory_requests }} G</span>
                                <span class="layui-badge layui-bg-gray" >/</span>
                                <span class="layui-badge layui-bg-green">可分配 {{ v.allocatable_memory }} G</span>
                                <span class="layui-badge layui-bg-gray">/</span>
                                <span class="layui-badge layui-bg-blue">总量 {{ v.capacity_memory }} G</span><br>
                                短暂存储：
                                <span class="layui-badge layui-bg-green">可分配 {{ v.allocatable_ephemeral_storage }} G</span>
                                <span class="layui-badge layui-bg-gray">/</span>
                                <span class="layui-badge layui-bg-blue">总量 {{ v.capacity_ephemeral_storage }} G</span><br>
                                Pod数量：
                                <span class="layui-badge layui-bg-green">已创建 {{ v.pods_number }} 个</span>
                                <span class="layui-badge layui-bg-gray">/</span>
                                <span class="layui-badge layui-bg-blue">总量 {{ v.capacity_pods }} 个</span><br>
                             </div>
                         </div>
                         </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

<!--js代码-->
{% block js %}
<script src="/static/js/echarts.min.js"></script>
<script src="/static/js/node-chart-index.js"></script>

<script>

layui.use('table', function(){
  var table = layui.table;
  var $ = layui.jquery;

    $.ajax({
        type: "GET",
        url: "{% url 'namespace_api' %}",
        timeout: 5000,
        async: false,
        success: function (res) {
            if(res.code == 0) {
                // 动态追加列表选项
                for(let index in res.data) {
                    row = res.data[index];
                    $("#dashboard-ns").append('<div class="dashboard-ns">' + row.name + '</div>')
                }
            } else if (res.code == 1) {
                $("#dashboard-ns").append('<span class="pv-notice">' + res.msg + '</span>')
            }
        },
        error: function (res) {
            $("#dashboard-ns").append('<span class="pv-notice">获取命名空间列表失败！<br>请检查K8s集群地址或者服务器网络.</span>')
        }
    });

    $.ajax({
       url: "{% url "node_resource" %}",
       type: 'GET',
       dataType: 'JSON',
       success: function (res) {
           var allocatable_cpu = 0; // 允许分配
           var allocatable_memory = 0;
           var cpu_requests = 0;   // 已分配
           var memory_requests = 0;
           var schedulable_ok = 0;
           var schedulable_no = 0;
           var status_ok = 0;
           var status_no = 0;
           for(key in res){
               allocatable_cpu += res[key]["allocatable_cpu"];
               allocatable_memory += res[key]["allocatable_memory"];
               cpu_requests += res[key]["cpu_requests"];
               memory_requests += res[key]["memory_requests"];
               if (res[key]["schedulable"]) {   // 布尔值判断，值是null或者true
                   schedulable_no  += 1
               } else {
                   schedulable_ok += 1
               }

               if (res[key]["status"]) {
                   status_ok  += 1
               } else {
                   status_no += 1
               }
           }
           cpu_percent = 100 * cpu_requests / allocatable_cpu;
           memory_percent = 100 * memory_requests / allocatable_memory ;
           node_total = (status_ok+status_no);
           status_percent = 100 * status_ok / node_total;
           schedulable_percent = 100 * schedulable_ok / node_total;
           // Node就绪
           option1.series[0].data[0].name = "Node状态：准备就绪 " + status_ok + " 台/总数 " + node_total + " 台";
           option1.series[0].data[0].value = status_percent.toFixed(1);
           myChart1.setOption(option1, true);
           // Node可调度
           option2.series[0].data[0].name = "Node调度：可调度 " + schedulable_ok + " 台/总数 " + node_total + " 台";
           option2.series[0].data[0].value = schedulable_percent.toFixed(1);
           myChart2.setOption(option2, true);
           // CPU
           option3.series[0].data[0].name = "CPU使用：已分配 " + cpu_requests.toFixed(1) + " 核/可分配 " + allocatable_cpu.toFixed(1) + " 核";
           option3.series[0].data[0].value = cpu_percent.toFixed(1);
           myChart3.setOption(option3, true);
           // 内存
           option4.series[0].data[0].name = "内存使用：已分配 " + memory_requests.toFixed(1) + " G/可分配 " + allocatable_memory.toFixed(1) + " G";
           option4.series[0].data[0].value = memory_percent.toFixed(1);
           myChart4.setOption(option4, true);
       }
   });

});

</script>

{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
    <script type="text/javascript" src="https://cdn.bootcdn.net/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <style>
        body {
            background-color: #edeff0;
        }

        .a {
            width: 900px;
            height: 400px;
            background-color: white;
            position: absolute;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
            margin: auto;
            box-shadow: 0 2px 1px -1px rgba(0, 0, 0, .2), 0 1px 1px 0 rgba(0, 0, 0, .14), 0 1px 3px 0 rgba(0, 0, 0, .12);
        }

        .c {
            height: 60px;
            width: 900px;
            background-color: #326de6;
            color: white;
            font-size: 20px;
        }

        .c p {
            padding-left: 300px;
            padding-top: 12px;
            font-weight: bold;
            font-size: 26px;
            letter-spacing: 1px;
        }

        .d, .e {
            padding-left: 300px;
            padding-top: 20px;
        }

        .d input, .e input {
            width: 300px;
            height: 25px;
            border-style: none;
            border-bottom: 1px solid black;
            outline: none;
            margin-top: 10px;
            margin-left: 10px;
        }

        #btn {
            height: 50px;
            width: 150px;
            margin-left: 375px;
            margin-top: 40px;
            border-style: none;
            font-size: 22px;
            background-color: #326de6;
            color: white;
            padding: 8px 15px 8px 15px;
            outline: none;
            box-shadow: 0 2px 1px -1px rgba(0, 0, 0, .2), 0 1px 1px 0 rgba(0, 0, 0, .14), 0 1px 3px 0 rgba(0, 0, 0, .12);
        }

        #btn:hover {
            cursor: pointer;
        }

    </style>
</head>
<body>
{% csrf_token %}
<div class="a">
    <div class="b">
        <div class="c">
            <p>欢迎访问Kubernetes管理平台</p>
        </div>
        <div>
            <div class="d">
                <p><input type="text" name="username" placeholder="输入用户名"></p>
            </div>
            <div class="e">
                <p><input type="password" name="password" placeholder="输入密码"></p>
            </div>
            <p>
                <button type="button" id="btn">登录</button>&nbsp;&nbsp;&nbsp;<span id="notice"></span></p>
        </div>
    </div>
</div>
<script type="text/javascript">
    $("#btn").click(function () {
        var csrf_token = $('[name="csrfmiddlewaretoken"]').val();
        var username = $("input[name='username']").val();
        var password = $("input[name='password']").val();
        // 判断输入是否为空
        if (!username) {
            $("#notice").html("请输入用户名！").css("color", "red");
            return
        }
        if (!password) {
            $("#notice").html("请输入密码！").css("color", "red");
            return
        }
        var data = {'username': username, 'password': password, 'csrfmiddlewaretoken': csrf_token};
        $.ajax({
            type: "POST",
            url: "/login/",
            timeout: 5000,
            dataType: "json",
            data: data,
            success: function (res) {
                if (res.code == 200) {
                    location.href = "/"
                } else if (res.code == 1) {
                    $("#notice").html(res.msg).css("color", "red");
                }
            },
            error: function (res) {
                $("#notice").html("服务器接口异常！").css("color", "red");
            }
        })
    })
</script>
</body>
</html>